### ISSUE TITLE
Investigate if Windows can detect and operate multiple BLE adapters

### ISSUE THREAD

**Issue by kdewald** [OpenBluetoothToolbox/SimpleBLE#102]

**Comment by eriklins** [comment]
I spent quite some time experimenting with two Bluetooth/BLE controllers with Windows 10 and it doesn't work. The Windows driver attempts to load only on the first radio enumerated by Plug and Play. It does return error code 10 on driver start for all other radios. If another radio should be used it's necessary to disable the first one in the device manager and then plug the second one. If pairing is required for certain BLE peripherals those have to be re-paired since pairing by design is per radio. Concurrent usage of multiple BLE radios is not possible. That was about two years ago, but I cannot find any references anywhere that this has changed recently.
