### ISSUE TITLE
Notify on single byte

### ISSUE THREAD

**Issue by Rasmus-Fink** [OpenBluetoothToolbox/SimpleBLE#256]
Hi,
Following the example notify.cpp:
I get notified when I send  a string via the serial terminal if I send a CR/LF. This is useful for sending a string. I need, however, to sends/receive binary data, so I essentially need the callback in notify.cpp to fire on every byte received. 
Is that possible using this library?
BR
Fink

**Comment by eriklins** [comment]
From the Bluetooth/BLE procotol perspective a notification is raised when a peripheral device did update a GATT characteristic and only one notification will be propagated from the underlying BLE stack towards any higher level library like SimpleBLE. This is fully independent on how many characters of the characteristic did change. The only (BLE protocol compliant) chance to get one notification per byte would be to write/notify single bytes instead of multiple into the characteristic on your peripheral subsequently.
If you plan to transfer binary data, a terminal would not be the proper implementation. You can update a characteristic with binary data without issues and no need for CR/LF. This is just for demonstrating in the sample application for ease of usage.
